//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTinTuc_v3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TAIKHOAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAIKHOAN()
        {
            this.DANGTINTUCs = new HashSet<DANGTINTUC>();
            this.SUATINs = new HashSet<SUATIN>();
        }
        [Display(Name = "Username")]
        [Required(ErrorMessage ="Username is not empty")]
        public string ID { get; set; }

        [Display(Name = "Password")]
        [Required(ErrorMessage = "Password is not empty")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public string LoaiTaiKhoan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANGTINTUC> DANGTINTUCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUATIN> SUATINs { get; set; }
    }
}
